import * as THREE from 'three';
import './style.css';
import {Duel} from './combat.js';
const $=id=>document.getElementById(id),duel=new Duel();
const scene=new THREE.Scene();scene.background=new THREE.Color('#101923');scene.fog=new THREE.FogExp2('#101923',.034);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('intro').innerHTML='<h2>WebGL unavailable</h2><p>Enable hardware acceleration or try another browser.</p>';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-10,10,6,-5,.1,100);camera.position.set(0,4.4,20);camera.lookAt(0,2,-2);
scene.add(new THREE.HemisphereLight('#92bed7','#181318',2.2));const moonlight=new THREE.DirectionalLight('#add8ee',3);moonlight.position.set(-5,10,-2);moonlight.castShadow=true;moonlight.shadow.mapSize.set(2048,2048);Object.assign(moonlight.shadow.camera,{left:-13,right:13,top:12,bottom:-10});scene.add(moonlight);
const material=(color,roughness=.8,metalness=.1)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const stone=material('#333f49'),dark=material('#17232e'),edge=material('#47515a'),gold=material('#9e783d',.5,.55);
function box(w,h,d,mat,x,y,z,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function cylinder(r1,r2,h,mat,x,y,z,parent=scene,n=10){const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,n),mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
box(30,.45,11,stone,0,-.3,-1);for(let x=-14;x<14;x+=1.8)for(let z=-5;z<4;z+=1.7){box(1.77,.07,1.67,material(['#39444b','#303a41','#354048'][Math.floor(Math.random()*3)]),x,-.04,z)}
for(let i=0;i<4;i++)box(19+i*1.1,.28,1.5,stone,0,-.05+i*.28,-5-i*.8);
box(23,1,1,dark,0,.5,-8);for(let x=-12;x<=12;x+=3){box(.3,1.8,.4,edge,x,1.2,-7.8);box(2.7,.15,.3,edge,x+1.5,1.65,-7.8)}
for(const x of [-10,-6.8,6.8,10]){box(1.5,.3,1.5,edge,x,.3,-5.5);cylinder(.46,.61,6.8,stone,x,3.8,-5.5);for(const y of [1,5.8,6.8])box(1.05,.25,1.05,edge,x,y,-5.5);box(1.65,.4,1.6,stone,x,7.25,-5.5);}
box(22,.6,1.5,dark,0,7.6,-5.5);box(23,.18,1.9,edge,0,8,-5.5);
// Temple portal and concentric carved stone rings.
box(5.5,5.6,.5,dark,0,3.9,-9);for(const x of [-2.8,2.8])box(.45,5.8,.8,edge,x,3.8,-8.7);box(6.5,.5,1,edge,0,6.6,-8.7);
for(const r of [1.9,2.15,2.28]){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.035,6,70),gold);ring.position.set(0,4,-8.35);scene.add(ring)}
const crest=new THREE.Group();crest.position.set(0,4,-8.25);scene.add(crest);for(let i=0;i<8;i++){const a=i*Math.PI/4;const shard=box(.12,.9,.08,gold,Math.sin(a)*1.15,Math.cos(a)*1.15,0,crest);shard.rotation.z=-a;}const diamond=box(.85,.85,.08,gold,0,0,0,crest);diamond.rotation.z=Math.PI/4;
// Distant moon and jagged mountain silhouettes.
const moon=new THREE.Mesh(new THREE.CircleGeometry(1.5,64),new THREE.MeshBasicMaterial({color:'#c1d4d7'}));moon.position.set(-4,7,-18);scene.add(moon);
for(let i=0;i<20;i++){const mountain=new THREE.Mesh(new THREE.ConeGeometry(2+Math.random()*3,3+Math.random()*5,4),material('#172a36'));mountain.position.set((i-10)*2,2,-16-Math.random()*3);scene.add(mountain)}
const flames=[];for(const x of [-8.3,8.3]){cylinder(.25,.5,1.5,dark,x,.75,-2);cylinder(.7,.28,.5,gold,x,1.65,-2);const light=new THREE.PointLight('#ff963b',18,10,2);light.position.set(x,2.5,-2);scene.add(light);for(let i=0;i<7;i++){const f=new THREE.Mesh(new THREE.ConeGeometry(.12+Math.random()*.16,.8+Math.random()*.5,5),new THREE.MeshBasicMaterial({color:i%2?'#ffb650':'#ed6c2a',transparent:true,opacity:.8}));f.position.set(x+(Math.random()-.5)*.65,2.2,-2+(Math.random()-.5)*.4);scene.add(f);flames.push(f)}}
function fighter(color){const root=new THREE.Group();scene.add(root);const cloth=material(color,.65,.25),black=material('#13191e'),skin=material('#a98871'),steel=material('#475462',.45,.6);const body=new THREE.Group();root.add(body);
box(.8,.95,.42,black,0,1.93,0,body);for(const x of [-.25,.25]){const sash=box(.24,.95,.48,cloth,x,1.98,.02,body);sash.rotation.z=x>0?-.14:.14}box(.78,.18,.48,steel,0,1.4,.02,body);box(.36,.6,.1,cloth,0,1.08,.28,body);box(.16,.16,.09,gold,0,1.43,.32,body);
const head=new THREE.Group();head.position.y=2.73;body.add(head);const hood=new THREE.Mesh(new THREE.SphereGeometry(.35,12,12),black);hood.scale.set(.92,1.14,.9);head.add(hood);box(.44,.17,.1,skin,0,.05,.285,head);box(.48,.25,.17,cloth,0,-.12,.29,head);for(const x of [-.13,.13])box(.1,.025,.015,new THREE.MeshBasicMaterial({color:'#e3f8ff'}),x,.065,.35,head);
function limb(x,y,len,isArm){const pivot=new THREE.Group();pivot.position.set(x,y,0);body.add(pivot);box(isArm?.25:.3,len,.32,isArm?skin:black,0,-len/2,0,pivot);box(isArm?.29:.34,len*.46,.38,isArm?steel:cloth,0,-len*.7,.015,pivot);if(!isArm)box(.39,.2,.5,black,.06,-len,.07,pivot);else box(.27,.23,.34,black,0,-len,.01,pivot);return pivot}
const arms=[limb(-.52,2.28,.85,true),limb(.52,2.28,.85,true)],legs=[limb(-.25,1.3,1.13,false),limb(.25,1.3,1.13,false)];return{root,body,head,arms,legs};}
const models=[fighter('#c58c28'),fighter('#267da6')];const particles=[];const particleGeo=new THREE.SphereGeometry(.055,5,4),fireMat=new THREE.MeshBasicMaterial({color:'#ffa33f'}),iceMat=new THREE.MeshBasicMaterial({color:'#91ecff'});
function burst(x,y,owner,count=18){for(let i=0;i<count;i++){const mesh=new THREE.Mesh(particleGeo,owner?iceMat:fireMat);mesh.position.set(x,y,.4);scene.add(mesh);particles.push({mesh,vx:(Math.random()-.5)*6,vy:(Math.random()-.15)*6,life:.3+Math.random()*.4})}}
const ambientGeo=new THREE.BufferGeometry(),ambientPos=new Float32Array(210*3);for(let i=0;i<210;i++){ambientPos[i*3]=(Math.random()-.5)*26;ambientPos[i*3+1]=Math.random()*12;ambientPos[i*3+2]=(Math.random()-.5)*15}ambientGeo.setAttribute('position',new THREE.BufferAttribute(ambientPos,3));const dust=new THREE.Points(ambientGeo,new THREE.PointsMaterial({color:'#adc8d3',size:.025,transparent:true,opacity:.5}));scene.add(dust);
const projectileMeshes=[];const projectileGeo=new THREE.IcosahedronGeometry(.23,1);let pendingAttack=[null,null],pendingJump=[false,false];let keys={},paused=false,muted=true,audio,shake=0,announcementTime=0;const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
function tone(freq=100,duration=.12){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(35,audio.currentTime+duration);gain.gain.setValueAtTime(.13,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}catch{}}
function sound(){muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';$('sound').setAttribute('aria-label',muted?'Enable sound':'Disable sound');tone(330)}
function start(){duel.start();paused=false;cpuAttackCooldown=0;keys={};pendingAttack=[null,null];pendingJump=[false,false];$('intro').classList.add('hidden');$('result').classList.add('hidden');$('pause-panel').classList.add('hidden');tone(180,.3)}
function pause(force){if(['intro','finished'].includes(duel.state))return;paused=force??!paused;keys={};pendingAttack=[null,null];pendingJump=[false,false];$('pause-panel').classList.toggle('hidden',!paused)}
$('start').onclick=start;$('rematch').onclick=start;$('pause').onclick=()=>pause();$('resume').onclick=()=>pause(false);$('sound').onclick=sound;
let helpWasPaused=false;$('help').onclick=()=>{helpWasPaused=paused;pause(true);$('instructions').showModal()};function closeHelp(){$('instructions').close()}$('close-help').onclick=closeHelp;$('got-it').onclick=closeHelp;$('instructions').addEventListener('close',()=>{if(!helpWasPaused)pause(false)});
const bindings=[{left:'a',right:'d',jump:'w',block:'s',punch:'j',kick:'k',special:'l'},{left:'arrowleft',right:'arrowright',jump:'arrowup',block:'arrowdown',punch:'1',kick:'2',special:'3'}];
const gameKeys=new Set(bindings.flatMap(binding=>Object.values(binding)));
function press(key){keys[key]=true;if(paused)return;bindings.forEach((binding,i)=>{for(const type of ['punch','kick','special'])if(key===binding[type])pendingAttack[i]=type;if(key===binding.jump)pendingJump[i]=true})}
function playerInput(i){const b=bindings[i];return{move:(keys[b.right]?1:0)-(keys[b.left]?1:0),jump:pendingJump[i]||keys[b.jump],block:keys[b.block],attack:pendingAttack[i]||(keys[b.special]?'special':keys[b.kick]?'kick':keys[b.punch]?'punch':null)}}
window.addEventListener('keydown',e=>{if($('instructions').open)return;const key=e.key.toLowerCase();if(gameKeys.has(key))e.preventDefault();if(e.repeat)return;if(key==='escape')pause();else if(key==='m')sound();else if(key==='enter'&&['intro','finished'].includes(duel.state))start();else if(gameKeys.has(key))press(key)});
window.addEventListener('keyup',e=>delete keys[e.key.toLowerCase()]);window.addEventListener('blur',()=>{keys={};pendingAttack=[null,null];pendingJump=[false,false];pause(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true)});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);press(b.dataset.key)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>delete keys[b.dataset.key])}
function resize(){const {width,height}=$('scene').getBoundingClientRect();renderer.setSize(width,height);const viewWidth=Math.max(20,11*width/height),viewHeight=viewWidth*height/width;camera.left=-viewWidth/2;camera.right=viewWidth/2;camera.top=viewHeight/2;camera.bottom=-viewHeight/2;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('scene'));resize();
let cpuMode=false,cpuAttackCooldown=0;function updateMode(){const button=$('mode-toggle');button.textContent=`MODE: ${cpuMode?'1 PLAYER VS CPU':'TWO PLAYERS'} · CHANGE`;button.setAttribute('aria-pressed',String(cpuMode));$('intro-copy').textContent=cpuMode?'Face Sub-Zero, controlled by the CPU.':'Two players. One keyboard. One ancient rivalry.';$('player-two-guide').innerHTML=cpuMode?'<b>CPU · SUB-ZERO</b>AI controlled opponent<br/>Choose two players to use the arrow keys and 1 2 3.':'<b>P2 · SUB-ZERO</b>Arrow keys · Move / jump / block<br/>1 2 3 · Punch / kick / ice';$('opponent-label').textContent=cpuMode?'CPU':'P2';document.querySelector('.touch-player:last-child').classList.toggle('cpu-hidden',cpuMode)}$('mode-toggle').onclick=()=>{cpuMode=!cpuMode;updateMode()};updateMode();
function cpuInput(dt){if(duel.state!=='fight')return{};cpuAttackCooldown=Math.max(0,cpuAttackCooldown-dt);const cpu=duel.fighters[1],player=duel.fighters[0],delta=player.x-cpu.x,distance=Math.abs(delta),toward=Math.sign(delta)||-1;const threatened=player.action&&['punch','kick'].includes(player.action.type)&&distance<=(player.action.type==='kick'?2.8:2.2);const incoming=duel.projectiles.some(projectile=>projectile.owner===0&&Math.abs(projectile.x-cpu.x)<2.2);if((threatened||incoming)&&cpu.y===0)return{block:true};let attack=null;if(cpuAttackCooldown<=0){if(cpu.energy>=100&&distance>2.5&&distance<8)attack='special';else if(distance<=2.35)attack=distance<1.65&&Math.random()<.35?'punch':'kick';if(attack)cpuAttackCooldown=attack==='special'?.95:.7+Math.random()*.35}return{move:distance>2.4?toward:distance<1.15?-toward*.45:0,attack}}
let last=performance.now(),elapsed=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;if(!paused){elapsed+=dt;const previous=duel.state;duel.step(dt,playerInput(0),cpuMode?cpuInput(dt):playerInput(1));pendingAttack=[null,null];pendingJump=[false,false];if(previous!==duel.state&&duel.state==='finished'){$('result').classList.remove('hidden');const won=duel.wins[0]>=2;$('result-title').textContent=won?'SCORPION WINS':'SUB-ZERO WINS';$('result-copy').textContent=won?'Scorpion claims the temple.':cpuMode?'Sub-Zero defeats Scorpion.':'Player 2 claims the temple.'}for(const event of duel.events){if(event.type==='hit'){burst(event.x,event.y,event.owner,event.blocked?7:24);shake=event.blocked?.025:.09;tone(event.blocked?190:80)}else if(event.type==='cast')tone(event.owner?620:220,.25);else if(event.type==='fight'){announce('FIGHT',.8);tone(150,.3)}else if(event.type==='round')announce(event.winner<0?'DRAW':event.winner===0?'SCORPION WINS':'SUB-ZERO WINS',2.3)}
 if(duel.state==='countdown'){$('announcement').textContent=`ROUND ${String(duel.round).padStart(2,'0')}`;announcementTime=.1}else{announcementTime-=dt;if(announcementTime<=0)$('announcement').textContent=''}
 for(let i=0;i<2;i++){const f=duel.fighters[i],m=models[i],a=f.action,phase=a?Math.sin(Math.min(1,a.t/(a.type==='punch'?.3:.52))*Math.PI):0;const walking=f.walk!==0;const walk=Math.sin(elapsed*12)*(walking?.5:.05);m.root.position.set(f.x,f.y,0);m.root.rotation.y=f.facing*.3;m.body.position.y=Math.sin(elapsed*3+i)*.035;m.body.rotation.z=f.stun>0?-.12*f.facing:0;m.arms[0].rotation.z=-.5+walk*.5;m.arms[1].rotation.z=1.0-walk*.5;m.legs[0].rotation.z=-.15+walk;m.legs[1].rotation.z=.15-walk;if(a){if(a.type==='kick')m.legs[f.facing>0?1:0].rotation.z=f.facing*phase*1.8;else m.arms[f.facing>0?1:0].rotation.z=f.facing*(.8+phase*1.1)}if(f.block){m.arms[0].rotation.z=-2.1;m.arms[1].rotation.z=2.1}if(f.y>0){m.legs[0].rotation.z=-.6;m.legs[1].rotation.z=.8}m.root.traverse(o=>{if(o.isMesh&&o.material.emissive)o.material.emissive.set(f.frozen>0?'#205b75':'#000000')});$('health'+i).style.width=f.hp+'%';$('meter'+i).style.width=f.energy+'%';$('energy'+i).textContent=f.energy>=100?'READY':'RECHARGING';$('wins'+i).textContent=[0,1].map(n=>duel.wins[i]>n?'●':'○').join(' ')}
 for(const p of particles){p.life-=dt;p.mesh.position.x+=p.vx*dt;p.mesh.position.y+=p.vy*dt;p.vy-=10*dt;p.mesh.scale.setScalar(Math.max(0,p.life*2))}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0){scene.remove(particles[i].mesh);particles.splice(i,1)}
 for(let i=0;i<flames.length;i++)flames[i].scale.set(1+Math.sin(elapsed*8+i)*.15,1+Math.sin(elapsed*12+i)*.25,1);dust.rotation.z=Math.sin(elapsed*.03)*.02;
 }
 while(projectileMeshes.length<duel.projectiles.length){const mesh=new THREE.Mesh(projectileGeo,fireMat);scene.add(mesh);projectileMeshes.push(mesh)}projectileMeshes.forEach((mesh,i)=>{const q=duel.projectiles[i];mesh.visible=!!q;if(q){mesh.position.set(q.x,q.y,.2);mesh.material=q.owner?iceMat:fireMat;mesh.rotation.z=elapsed*8;if(!paused)burst(q.x,q.y,q.owner,1)}});
 shake*=.85;camera.position.x=reducedMotion?0:(Math.random()-.5)*shake;$('timer').textContent=String(Math.ceil(duel.time)).padStart(2,'0');$('round').textContent=`ROUND ${String(duel.round).padStart(2,'0')}`;$('status').textContent=paused?'DUEL PAUSED':duel.state==='intro'?'AWAITING CHALLENGER':duel.state==='finished'?'DUEL COMPLETE':`${cpuMode?'1 PLAYER VS CPU':'2 PLAYERS'} · FIRST TO TWO WINS`;renderer.render(scene,camera);
}function announce(text,time){$('announcement').textContent=text;announcementTime=time}requestAnimationFrame(frame);
